// <auto-generated />
namespace TrashCollector.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MadetheDateTimesinCustomernullable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MadetheDateTimesinCustomernullable));
        
        string IMigrationMetadata.Id
        {
            get { return "201810251807554_Made the DateTimes in Customer nullable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
