// <auto-generated />
namespace TrashCollector.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddedLatitudeLongitudeupdateLatitudeAndLongitudeAsyncandsomeprivatethingstoCustomercsmodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedLatitudeLongitudeupdateLatitudeAndLongitudeAsyncandsomeprivatethingstoCustomercsmodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201811011816003_Added Latitude, Longitude, updateLatitudeAndLongitudeAsync(), and some private things to Customer.cs (model)"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
